# base image 
FROM ubuntu:latest

# Operationas & Installing Libraries
RUN <> &&

#  Copy the code
COPY  ./ /usr/appl

# Expose nthe ports for networking

EXPOSE 80


# ENTRYPOINT or CMD to start application
CMD ["python3","/usr/app/test.py"]

