# Example 5 - RUN
FROM ubuntu:latest

RUN apt-get -y update && apt-get -y install nginx python3
#RUN yum -y update && yum -y install nginix python3

EXPOSE 80
#Command - Overwritten
# can only be run in to -it mode
CMD ["/bin/bash"]

